services:
  tailorcv-accp:
    build:
      context: .
      target: runner
    container_name: tailorcv-accp
    restart: unless-stopped
    env_file: .env.accp
    ports:
      - "3101:3000"
    networks:
      - infrastructure_proxy
      - tailorcv_db_network

  tailorcv-accp-migrate:
    build:
      context: .
      target: migrator
    env_file: .env.accp
    networks:
      - tailorcv_db_network
    profiles:
      - migrate

networks:
  infrastructure_proxy:
    external: true
  tailorcv_db_network:
    external: true
